Feature: Service consumer - Checkout

  Background: Checkout
    Given the User "MMAdmin001" is Signed In
    And the IAM User @me request has been intercepted to return the User "001"
    And the IAM User request has been intercepted to return the User "001"
    And the IAM Organization request has been intercepted to return the Organization "001" for SP "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the Billing and Invoicing request has been intercepted to return the billing details for the Agreement "004" of Service Consumer "001"
    And the Contracting request has been intercepted to return the legal document type "001" for the Agreement Type "007" of Service Consumer "001"

  Scenario: Checkout Page is rendered correctly with all the information displayed
    Given the Billing and Invoicing request has been intercepted to return the billing address "001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    When the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    Then the Element with Cypress ID "checkout-heading" should have the text as "Purchase SP License"
    And the Element with Cypress ID "checkout-price-amount" should have the text as "€ 10"
    And the Element with Cypress ID "checkout-agreement-type-name" should have the text as "Agreement Type 004"
    And the Element with Cypress ID "checkout-agreement-type-description" should have the text as "Agreement Type 004 Description"
    And the Element with Cypress ID "checkout-subtotal-amount" should have the text as "€ 10"
    And the Element with Cypress ID "checkout-total-due-amount" should have the text as "€ 10"
    And the Element with Cypress ID "checkout-billing-address-form" should be visible
    And the Element with Cypress ID "checkout-total-due-amount" should have the text as "€ 10"
    And the Input with Cypress ID "input-country" should have value as "Netherlands"
    And the Input with Cypress ID "input-address-line-1" should have value as "Simsekstraat 2z"
    And the Input with Cypress ID "input-address-line-2" should have value as "de Gruijlstraat 9"
    And the Input with Cypress ID "input-postal-code" should have value as "1674PG"
    And the Input with Cypress ID "input-city-town" should have value as "Bosch en Duin"

  Scenario: Checkout Page flow is executed successfully with proper form validation
    Given the Billing and Invoicing request has been intercepted to return the billing address "emptyAddress" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the Element with Cypress ID "input-country" should have a Form Error for validator "required" with text "Country is required"
    And the Element with Cypress ID "input-address-line-1" should have a Form Error for validator "required" with text "Address Line 1 is required"
    And the Element with Cypress ID "input-postal-code" should have a Form Error for validator "required" with text "Postal code is required"
    And the Element with Cypress ID "input-city-town" should have a Form Error for validator "required" with text "Town or city required"
    And the User types "Belgium" in the Element with Cypress ID "input-country"
    And the User types "Simsekstraat 2z" in the Element with Cypress ID "input-address-line-1"
    And the User types "de Gruijlstraat 9" in the Element with Cypress ID "input-address-line-2"
    And the User types "1674PG" in the Element with Cypress ID "input-postal-code"
    And the User types "Bosch en Duin" in the Element with Cypress ID "input-city-town"
    And the Billing and Invoicing request has been intercepted to update and return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the billing request has been intercepted to initialize checkout for the invoice "3fa85f64-5717-4562-b3fc-2c963f66afa6" and Service Consumer "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the User clicks on the Element with Cypress ID "button-checkout-submit-payment"
    And the Element with Cypress ID "checkout-license-legal-documents" should have a class "error"
    When the User clicks on the Element with Cypress ID "checkbox-document-0"
    Then the Element with Cypress ID "checkout-license-legal-documents" should NOT have a class "error"

  Scenario: Success should redirect to license details view with success modal
    Given the Billing and Invoicing request has been intercepted to return the billing address "emptyAddress" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    And the User types "Belgium" in the Element with Cypress ID "input-country"
    And the User types "Simsekstraat 2z" in the Element with Cypress ID "input-address-line-1"
    And the User types "de Gruijlstraat 9" in the Element with Cypress ID "input-address-line-2"
    And the User types "1674PG" in the Element with Cypress ID "input-postal-code"
    And the User types "Bosch en Duin" in the Element with Cypress ID "input-city-town"
    And the Billing and Invoicing request has been intercepted to update and return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the billing request has been intercepted to initialize checkout for the invoice "3fa85f64-5717-4562-b3fc-2c963f66afa6" and Service Consumer "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the User clicks on the Element with Cypress ID "button-checkout-submit-payment"
    And the Element with Cypress ID "checkout-license-legal-documents" should have a class "error"
    When the User clicks on the Element with Cypress ID "checkbox-document-0"
    And the Stripe retrievePaymentIntent request has been intercepted with status "succeeded"
    And the IAM Organization request has been intercepted to return the Organization "001"
    Then the User navigates to "/"
    And the Policies Service Consumers Agreements request has been intercepted to return the License "001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User navigates to "/?license_id=86678c73-b72a-4c8e-9dca-0bf5d1a1c6a1&payment_intent=pi_3QKdrcEVWnWNTxcV1UcGEeR3&payment_intent_client_secret=pi_3QKdrcEVWnWNTxcV1UcGEeR3_secret_E08OpQ92hHQqAUnanVdxhvQLd&redirect_status=succeeded"
    Then the Element with Cypress ID "dialog-payment-successful" should exist
    When the User clicks on the Element with Cypress ID "button-payment-successful"
    Then the Element with Cypress ID "dialog-payment-successful" should NOT exist
  
  Scenario: Payment failed should redirect to license details view with payment failed modal
    Given the Billing and Invoicing request has been intercepted to return the billing address "emptyAddress" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    And the User types "Belgium" in the Element with Cypress ID "input-country"
    And the User types "Simsekstraat 2z" in the Element with Cypress ID "input-address-line-1"
    And the User types "de Gruijlstraat 9" in the Element with Cypress ID "input-address-line-2"
    And the User types "1674PG" in the Element with Cypress ID "input-postal-code"
    And the User types "Bosch en Duin" in the Element with Cypress ID "input-city-town"
    And the Billing and Invoicing request has been intercepted to update and return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the billing request has been intercepted to initialize checkout for the invoice "3fa85f64-5717-4562-b3fc-2c963f66afa6" and Service Consumer "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the User clicks on the Element with Cypress ID "button-checkout-submit-payment"
    And the Element with Cypress ID "checkout-license-legal-documents" should have a class "error"
    When the User clicks on the Element with Cypress ID "checkbox-document-0"
    And the Stripe retrievePaymentIntent request has been intercepted with status "error"
    And the IAM Organization request has been intercepted to return the Organization "001"
    Then the User navigates to "/"
    And the Policies Service Consumers Agreements request has been intercepted to return the License "001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User navigates to "/?license_id=86678c73-b72a-4c8e-9dca-0bf5d1a1c6a1&payment_intent=pi_3QKe0UEVWnWNTxcV0SCVTTmh&payment_intent_client_secret=pi_3QKe0UEVWnWNTxcV0SCVTTmh_secret_TJcqrOmNs4dlIjnECZfh4mYqD&redirect_status=failed"
    Then the Element with Cypress ID "dialog-payment-failed" should exist
    When the User clicks on the Element with Cypress ID "button-payment-try-again"
    Then the User should be redirected to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a1"

  Scenario: Checkout with Billing type Once Off should successfully see a message
    Given the Billing and Invoicing request has been intercepted to return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the Billing and Invoicing request has been intercepted to return the billing details for the Agreement "003" of Service Consumer "001"
    And the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    And the User types "Belgium" in the Element with Cypress ID "input-country"
    And the User types "Simsekstraat 2z" in the Element with Cypress ID "input-address-line-1"
    And the User types "de Gruijlstraat 9" in the Element with Cypress ID "input-address-line-2"
    And the User types "1674PG" in the Element with Cypress ID "input-postal-code"
    And the User types "Bosch en Duin" in the Element with Cypress ID "input-city-town"
    And the Billing and Invoicing request has been intercepted to update and return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the billing request has been intercepted to initialize checkout for the invoice "3fa85f64-5717-4562-b3fc-2c963f66afa6" and Service Consumer "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the User clicks on the Element with Cypress ID "button-checkout-submit-payment"
    Then the Element with Cypress ID "checkout-billing-type" should have the text as "This is a once-off charge."
    
  Scenario: Checkout with Billing type Recurring should successfully see a message
    Given the Billing and Invoicing request has been intercepted to return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the Billing and Invoicing request has been intercepted to return the billing details for the Agreement "005" of Service Consumer "001"
    And the User navigates to "/checkout/86678c73-b72a-4c8e-9dca-0bf5d1a1c6a2"
    And the User types "Belgium" in the Element with Cypress ID "input-country"
    And the User types "Simsekstraat 2z" in the Element with Cypress ID "input-address-line-1"
    And the User types "de Gruijlstraat 9" in the Element with Cypress ID "input-address-line-2"
    And the User types "1674PG" in the Element with Cypress ID "input-postal-code"
    And the User types "Bosch en Duin" in the Element with Cypress ID "input-city-town"
    And the Billing and Invoicing request has been intercepted to update and return the billing address "Updated001" from Organization "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the billing request has been intercepted to initialize checkout for the invoice "3fa85f64-5717-4562-b3fc-2c963f66afa6" and Service Consumer "4a6f01d0-f3c6-4923-ad98-112d6d97355b"
    And the User clicks on the Element with Cypress ID "button-submit-checkout-billing-address"
    And the User clicks on the Element with Cypress ID "button-checkout-submit-payment"
    Then the Element with Cypress ID "checkout-billing-type" should have the text as "Card will automatically be billed on this day every month unless subscription is cancelled."